import { useEffect, useState } from "react";
import DashboardLayout from "../components/layout/DashboardLayout";
import { createCampaign, deleteCampaign, getManageCampaigns, updateCampaign, getCampaignStats, verifyCampaign, verifyCampaignParticipation } from "../api/reportApi";
import toast from "react-hot-toast";

const empty = { title:"", description:"", location:"", latitude:"", longitude:"", date:"", startDate:"", endDate:"", rewardPoints:20, maxParticipants:"", source:"", organizerContact:"" };

export default function CampaignAdminPage(){
  const user=JSON.parse(localStorage.getItem("user")||"null");
  const isAdmin=user?.role==="admin";
  const [items,setItems]=useState([]); const [stats,setStats]=useState({total:0,upcoming:0,active:0,completed:0,pendingVerification:0,totalParticipants:0});
  const [form,setForm]=useState(empty); const [editing,setEditing]=useState(""); const [loading,setLoading]=useState(false);
  const load=async()=>{const [c,s]=await Promise.all([getManageCampaigns(),getCampaignStats()]);setItems(c.data);setStats(s.data)};
  useEffect(()=>{load().catch(()=>toast.error("Failed to load campaigns"))},[]);
  const change=e=>setForm({...form,[e.target.name]:e.target.value});
  const submit=async e=>{e.preventDefault();setLoading(true);try{const payload={...form,rewardPoints:Number(form.rewardPoints),maxParticipants:form.maxParticipants?Number(form.maxParticipants):undefined,latitude:form.latitude?Number(form.latitude):undefined,longitude:form.longitude?Number(form.longitude):undefined};if(!payload.startDate)payload.startDate=payload.date;if(!payload.endDate)payload.endDate=payload.date;if(editing)await updateCampaign(editing,payload);else await createCampaign(payload);toast.success(editing?"Campaign updated":"Campaign submitted");setForm(empty);setEditing("");await load()}catch(e){toast.error(e.response?.data?.message||"Operation failed")}finally{setLoading(false)}};
  const edit=c=>{setEditing(c._id);setForm({title:c.title,description:c.description,location:c.location,latitude:c.latitude??"",longitude:c.longitude??"",date:new Date(c.date).toISOString().slice(0,10),startDate:c.startDate?new Date(c.startDate).toISOString().slice(0,10):"",endDate:c.endDate?new Date(c.endDate).toISOString().slice(0,10):"",rewardPoints:c.rewardPoints||20,maxParticipants:c.maxParticipants||"",source:c.source||"",organizerContact:c.organizerContact||""})};
  const remove=async id=>{if(!confirm("Delete this campaign?"))return;try{await deleteCampaign(id);toast.success("Campaign deleted");await load()}catch(e){toast.error(e.response?.data?.message||"Delete failed")}};
  const approve=async id=>{try{await verifyCampaign(id);toast.success("Campaign verified and published");await load()}catch(e){toast.error(e.response?.data?.message||"Verification failed")}};
  const verify=async(c,userId)=>{try{const r=await verifyCampaignParticipation(c._id,userId);toast.success(`Participation verified. +${r.data.rewardPoints} points`);await load()}catch(e){toast.error(e.response?.data?.message||"Verification failed")}};
  return <DashboardLayout><div className="max-w-7xl mx-auto pb-10"><div className="mb-7"><p className="text-sky-600 font-semibold">{isAdmin?"ADMINISTRATION":"VOLUNTEER"}</p><h1 className="text-3xl font-bold">Campaign Management</h1><p className="text-gray-500 mt-1">Only volunteers and administrators can create campaigns. Volunteer campaigns require administrator verification before publication.</p></div>
  <div className="grid sm:grid-cols-2 lg:grid-cols-6 gap-4 mb-6">{[["Total",stats.total],["Pending",stats.pendingVerification],["Upcoming",stats.upcoming],["Active",stats.active],["Completed",stats.completed],["Participants",stats.totalParticipants]].map(([l,v])=><div key={l} className="bg-white border rounded-2xl p-4"><p className="text-sm text-gray-500">{l}</p><p className="text-2xl font-bold mt-1">{v??0}</p></div>)}</div>
  <div className="grid lg:grid-cols-3 gap-6"><form onSubmit={submit} className="bg-white border rounded-2xl p-6 shadow-sm h-fit"><h2 className="text-xl font-bold mb-4">{editing?"Edit campaign":"Create campaign"}</h2>{[["title","Title"],["location","Location"],["source","Real-world source / reference"],["organizerContact","Organizer contact"]].map(([n,ph])=><input key={n} name={n} value={form[n]} onChange={change} required={n==="title"||n==="location"} placeholder={ph} className="w-full border rounded-lg p-3 mb-3"/>)}<textarea name="description" value={form.description} onChange={change} required maxLength="1000" placeholder="Description" rows="4" className="w-full border rounded-lg p-3 mb-3"/><div className="grid grid-cols-2 gap-2 mb-3">{[["latitude","Latitude"],["longitude","Longitude"]].map(([n,ph])=><input key={n} type="number" step="any" name={n} value={form[n]} onChange={change} placeholder={ph} className="border rounded-lg p-3"/>)}</div><label className="text-sm text-gray-600">Event date</label><input type="date" name="date" value={form.date} onChange={change} required className="w-full border rounded-lg p-3 mb-3"/><div className="grid grid-cols-2 gap-2"><input type="date" name="startDate" value={form.startDate} onChange={change} className="border rounded-lg p-3"/><input type="date" name="endDate" value={form.endDate} onChange={change} className="border rounded-lg p-3"/></div><div className="grid grid-cols-2 gap-2 my-3"><input type="number" min="0" max="10000" name="rewardPoints" value={form.rewardPoints} onChange={change} placeholder="Reward points" className="border rounded-lg p-3"/><input type="number" min="1" name="maxParticipants" value={form.maxParticipants} onChange={change} placeholder="Participant limit" className="border rounded-lg p-3"/></div><button disabled={loading} className="w-full bg-sky-600 disabled:bg-sky-300 text-white py-3 rounded-xl font-semibold">{loading?"Saving...":editing?"Save changes":"Create campaign"}</button>{editing&&<button type="button" onClick={()=>{setEditing("");setForm(empty)}} className="w-full mt-2 py-2">Cancel</button>}</form>
  <div className="lg:col-span-2 space-y-4">{items.map(c=><div key={c._id} className="bg-white border rounded-2xl p-5"><div className="flex justify-between gap-4"><div><div className="flex flex-wrap gap-2 items-center"><h2 className="font-bold text-lg">{c.title}</h2><span className="text-xs bg-slate-100 rounded-full px-3 py-1">{c.status}</span></div><p className="text-gray-500 mt-1">{c.location} · {new Date(c.date).toLocaleDateString()}</p><p className="text-sm mt-2">+{c.rewardPoints||0} points · {c.participantCount||0}{c.maxParticipants?`/${c.maxParticipants}`:""} participants</p></div><div className="flex gap-2 flex-wrap justify-end"><button onClick={()=>edit(c)} className="px-3 py-2 border rounded-lg">Edit</button><button onClick={()=>remove(c._id)} className="px-3 py-2 bg-red-600 text-white rounded-lg">Delete</button>{isAdmin&&!c.verifiedAt&&<button onClick={()=>approve(c._id)} className="px-3 py-2 bg-emerald-600 text-white rounded-lg">Verify & Publish</button>}</div></div><p className="text-gray-600 mt-3">{c.description}</p>{c.source&&<p className="text-xs text-gray-500 mt-2">Source: {c.source}</p>}{c.participants?.length>0&&<div className="mt-4 border-t pt-3"><p className="text-sm font-semibold mb-2">Participation verification</p><div className="flex flex-wrap gap-2">{c.participants.map(participant=><button key={participant._id||participant} onClick={()=>verify(c,participant._id||participant)} className="text-xs border rounded-lg px-3 py-2 hover:bg-slate-50">Verify {participant.name||String(participant).slice(-6)}</button>)}</div></div>}</div>)}{!items.length&&<div className="bg-white p-10 rounded-2xl text-center text-gray-500">No campaigns yet.</div>}</div></div></div></DashboardLayout>
}
