import { useEffect, useState } from "react";
import DashboardLayout from "../components/layout/DashboardLayout";
import { getVolunteerApplications, reviewVolunteerApplication } from "../api/volunteerApi";
import toast from "react-hot-toast";

export default function VolunteerApplicationsAdminPage() {
  const [items,setItems]=useState([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [notes,setNotes]=useState({});
  const load=()=>{setLoading(true);getVolunteerApplications().then(r=>setItems(r.data)).catch(e=>toast.error(e.response?.data?.message||"Failed to load applications")).finally(()=>setLoading(false));};
  useEffect(load,[]);
  const review=async(id,status)=>{setBusy(id);try{await reviewVolunteerApplication(id,{status,adminNote:notes[id]||""});toast.success(`Application ${status.toLowerCase()}`);load();}catch(e){toast.error(e.response?.data?.message||"Review failed")}finally{setBusy("")}};
  return <DashboardLayout><div className="max-w-6xl mx-auto pb-10"><div className="mb-7"><p className="text-sky-600 font-semibold">ADMINISTRATION</p><h1 className="text-3xl font-bold">Volunteer Applications</h1><p className="text-slate-500 mt-1">Approve trusted community members before giving them campaign creation access.</p></div>{loading?<div className="text-slate-500">Loading...</div>:<div className="space-y-4">{items.map(a=><div key={a._id} className="bg-white border rounded-2xl p-6"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-xl font-bold">{a.user?.name}</h2><p className="text-sm text-slate-500">{a.user?.email} · Applied {new Date(a.createdAt).toLocaleDateString()}</p></div><span className={`px-3 py-1 rounded-full text-xs font-semibold ${a.status==='Pending'?'bg-amber-100 text-amber-700':a.status==='Approved'?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{a.status}</span></div><div className="grid md:grid-cols-3 gap-4 mt-5"><div><p className="text-xs font-semibold text-slate-400">REASON</p><p className="mt-1 text-slate-700">{a.reason}</p></div><div><p className="text-xs font-semibold text-slate-400">EXPERIENCE</p><p className="mt-1 text-slate-700">{a.experience||"Not provided"}</p></div><div><p className="text-xs font-semibold text-slate-400">AVAILABILITY</p><p className="mt-1 text-slate-700">{a.availability||"Not provided"}</p></div></div>{a.status==='Pending'&&<div className="mt-5 flex flex-wrap gap-3"><input value={notes[a._id]||""} onChange={e=>setNotes({...notes,[a._id]:e.target.value})} placeholder="Optional admin note" className="flex-1 min-w-64 border rounded-lg px-3 py-2"/><button disabled={busy===a._id} onClick={()=>review(a._id,'Approved')} className="px-4 py-2 rounded-lg bg-emerald-600 text-white font-semibold">Approve</button><button disabled={busy===a._id} onClick={()=>review(a._id,'Rejected')} className="px-4 py-2 rounded-lg bg-red-600 text-white font-semibold">Reject</button></div>}</div>)}{!items.length&&<div className="bg-white border rounded-2xl p-10 text-center text-slate-500">No volunteer applications.</div>}</div>}</div></DashboardLayout>;
}
